version: "3.8"

services:
  node0:
    image: ${REAM_IMAGE:-ghcr.io/reamlabs/ream:latest}
    container_name: ream-node0
    command: >
      --data-dir /data
      lean_node
      --network /genesis/config.yaml
      --validator-registry-path /genesis/validators.yaml
      --node-id ream_0
      --private-key-path /config/keys/node0.key
      --socket-address 172.20.0.10
      --socket-port 9000
      --http-address 0.0.0.0
      --http-port 5052
      --http-allow-origin
      --bootnodes /genesis/nodes.yaml
      --metrics
      --metrics-address 0.0.0.0
      --metrics-port 8080
    ports:
      - "9000:9000/udp"
      - "5052:5052"
      - "8080:8080"
    volumes:
      - ./config:/config:ro
      - ./genesis:/genesis:ro
      - node0-data:/data
    networks:
      ream-network:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  node1:
    image: ${REAM_IMAGE:-ghcr.io/reamlabs/ream:latest}
    container_name: ream-node1
    command: >
      --data-dir /data
      lean_node
      --network /genesis/config.yaml
      --validator-registry-path /genesis/validators.yaml
      --node-id ream_1
      --private-key-path /config/keys/node1.key
      --socket-address 172.20.0.11
      --socket-port 9000
      --http-address 0.0.0.0
      --http-port 5052
      --http-allow-origin
      --bootnodes /genesis/nodes.yaml
      --metrics
      --metrics-address 0.0.0.0
      --metrics-port 8080
    ports:
      - "9001:9000/udp"
      - "5053:5052"
      - "8081:8080"
    volumes:
      - ./config:/config:ro
      - ./genesis:/genesis:ro
      - node1-data:/data
    networks:
      ream-network:
        ipv4_address: 172.20.0.11
    depends_on:
      - node0
    restart: unless-stopped

  node2:
    image: ${REAM_IMAGE:-ghcr.io/reamlabs/ream:latest}
    container_name: ream-node2
    command: >
      --data-dir /data
      lean_node
      --network /genesis/config.yaml
      --validator-registry-path /genesis/validators.yaml
      --node-id ream_2
      --private-key-path /config/keys/node2.key
      --socket-address 172.20.0.12
      --socket-port 9000
      --http-address 0.0.0.0
      --http-port 5052
      --http-allow-origin
      --bootnodes /genesis/nodes.yaml
      --metrics
      --metrics-address 0.0.0.0
      --metrics-port 8080
    ports:
      - "9002:9000/udp"
      - "5054:5052"
      - "8082:8080"
    volumes:
      - ./config:/config:ro
      - ./genesis:/genesis:ro
      - node2-data:/data
    networks:
      ream-network:
        ipv4_address: 172.20.0.12
    depends_on:
      - node0
      - node1
    restart: unless-stopped

  node3:
    image: g11tech/zeam:latest
    container_name: zeam-node3
    command: >
      --security-opt seccomp=unconfined 
      node 
      --data-dir /data 
      --custom_genesis /genesis 
      --validator_config /genesis/validator-config.yaml 
      --node-id zeam_3 
      --node-key /config/keys/node3.key
    ports:
      - "9003:9000/udp"
      - "5055:5052"
      - "8083:8080"
    volumes:
      - ./config:/config:ro
      - ./genesis:/genesis:ro
      - node3-data:/data
    networks:
      ream-network:
        ipv4_address: 172.20.0.13
    depends_on:
      - node0
      - node1
      - node2
    restart: unless-stopped

networks:
  ream-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

volumes:
  node0-data:
  node1-data:
  node2-data:
  node3-data:
